name: get kp index

on:
  schedule:
  - cron: "5 * * * *" # Runs at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- name: Checkout repository
      #  uses: actions/checkout@v2
      #  with:
      #    token: ${{ secrets.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run minute search
        run:
          python search.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update kp.json"
          git push
