name: get kp index

on:
  schedule:
  - cron: "0 * * * *" # Runs at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run minute search
        run: |
          python search.py > new_kp.json
          if ! cmp -s new_kp.json data/kp.json; then
            mv new_kp.json data/kp.json
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add data/kp.json
            git commit -m "Update kp.json"
            git push
          fi
